### ISSUE TITLE
Model adaption for Movable object segmentation

### ISSUE THREAD

**Issue by fatemechangizian** [PRBonn/4DMOS#23]
Hello,

Firstly thanks for the nice work.

I understand that the model is designed to segment only **moving** objects by considering receding windows but I would like to know if it's possible to adapt the current model to be able to segment any "**movable**" objects (objects with the ability to move - even parked cars or static person)?
(However, I see that leveraging the problem into segmenting any movable objects instead of moving objects can be seen as naive semantic segmentation of all object classes but I believe still having the idea of receding windows will improve the performance.)

**Comment by benemer** [comment]
Hey,

that's a very interesting question! Indeed, the model is designed to segment objects that move within the considered temporal horizon of past scans. If an object temporarily stops at an intersection and our window of past scans is too small, we are not able to realize it was moving before. In contrast, the SemanticKITTI labels for example will be _moving_, because the object _has moved_ within the sequence.

It probably depends on the task how to decide if an object is _movable_. You are right, one direction could be to decide based on the semantic class. Another one could be to have multiple measurements from an environment from different points in time and checking which parts are consistent. With this, a parked car on a parking spot that was free at another point in time could be detected.

It would be possible to feed 4DMOS with such a point cloud containing aligned scans from different points in time, but I never tried this.
