### ISSUE TITLE
Apollo dataset fine tune loss nan

### ISSUE THREAD

**Issue by momoshiki1** [PRBonn/4DMOS#37]
I used 4DMOS to perform fine tuning on the Apollo dataset, but shortly after starting training, I encountered a loss nan issue. Have you ever tried using 4DMOS to perform fine tuning on the Apollo dataset before?

**Comment by benemer** [comment]
Are you fine-tuning on Apollo or training from scratch?

I trained 4DMOS on multiple other datasets and sensors and did not encounter this issue. The problem with the Apollo labels is that only moving objects are labeled, and the remaining points are unlabeled (class id 0) instead of being considered static. Since unlabeled points will be ignored for training, the model only sees positive samples (e.g. moving) for training.

You can try again changing [this](https://github.com/PRBonn/4DMOS/blob/b04651abb4f7f6ccc306d6e3bf345831348cc9f2/config/semantic-kitti-mos.yaml#L116) line and remap the id 0 to static. This will considered unlabeled points as static.
